-- MySQL Script generated by MySQL Workbench
-- Fri 17 Jun 2022 06:01:44 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id_user` VARCHAR(45) GENERATED ALWAYS AS (),
  PRIMARY KEY (`id_user`));


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `firm` TEXT(255) NOT NULL,
  `model` TEXT(255) NOT NULL,
  `color` TEXT(255) NOT NULL,
  `year` YEAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id` VARCHAR(45) GENERATED ALWAYS AS (),
  `user_id_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `user_id_user`),
  INDEX `fk_car_user_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_car_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`user_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_1` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`goods` (
  `idgoods` INT GENERATED ALWAYS AS (),
  `price` DOUBLE NOT NULL,
  `name` TEXT(255) NOT NULL,
  `category` TEXT(255) NULL,
  PRIMARY KEY (`idgoods`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_goods` (
  `user_id_user` VARCHAR(45) NOT NULL,
  `goods_idgoods` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `goods_idgoods`),
  INDEX `fk_user_has_goods_goods1_idx` (`goods_idgoods` ASC) VISIBLE,
  INDEX `fk_user_has_goods_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_goods_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_goods_goods1`
    FOREIGN KEY (`goods_idgoods`)
    REFERENCES `mydb`.`goods` (`idgoods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`inspection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inspection` (
  `idinspection` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `support` TEXT(255) NOT NULL,
  PRIMARY KEY (`idinspection`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inspection_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inspection_has_user` (
  `inspection_idinspection` INT NOT NULL,
  `user_id_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`inspection_idinspection`, `user_id_user`),
  INDEX `fk_inspection_has_user_user1_idx` (`user_id_user` ASC) VISIBLE,
  INDEX `fk_inspection_has_user_inspection1_idx` (`inspection_idinspection` ASC) VISIBLE,
  CONSTRAINT `fk_inspection_has_user_inspection1`
    FOREIGN KEY (`inspection_idinspection`)
    REFERENCES `mydb`.`inspection` (`idinspection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inspection_has_user_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
